### ISSUE TITLE
add H266/VVC support

### ISSUE THREAD

**Issue by Ciancy28** [AnimMouse/ffmpeg-autobuild#1072]
ffmpeg 7.1 introduced h266 support
--enable-libvvdec and --enable-libvvenc should be added to the build parameters for it to be included i think

**Comment by AnimMouse** [comment]
Since this repository only builds on what rdp/ffmpeg-windows-build-helpers has, I recommend that you create an issue separately on [rdp/ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers/issues) about adding support for H266/VVC.
