### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by tooruu** [AnimMouse/ffmpeg-autobuild#1074]
I compared with gyan.dev and BtbN builds, and this one seems to be missing these feature flags:
`--enable-bzlib --enable-chromaprint --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-d3d12va --enable-dxva2 --enable-ffnvcodec --enable-iconv --enable-ladspa --enable-libcdio --enable-libcodec2 --enable-libdvdnav --enable-libdvdread --enable-libharfbuzz --enable-libjxl --enable-libkvazaar --enable-liblc3 --enable-liblensfun --enable-libopenmpt --enable-libplacebo --enable-libqrencode --enable-libquirc --enable-librav1e --enable-librist --enable-libshaderc --enable-libshine --enable-libssh --enable-libuavs3d --enable-libvpl --enable-libvvenc --enable-libxevd --enable-libxeve --enable-libzmq --enable-lv2 --enable-lzma --enable-mediafoundation --enable-openal --enable-opencl --enable-pthreads --enable-schannel --enable-sdl2 --enable-vaapi --enable-vulkan --enable-zlib`
Why are these not included?

**Comment by AnimMouse** [comment]
Since this repository only builds on what rdp/ffmpeg-windows-build-helpers has, I recommend that you create an issue separately on [rdp/ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers/issues) about adding support for those features.

**Comment by tooruu** [comment]
Thanks for your reply!

**Comment by AnimMouse** [comment]
You're welcome!
