### ISSUE TITLE
GPL and nonfree builds are identical

### ISSUE THREAD

**Issue by 9001** [AnimMouse/ffmpeg-autobuild#116]
it appears the GPL builds are duplicates of the nonfree builds

**Comment by AnimMouse** [comment]
Woah, I taught ffmpeg-windows-build-helpers provides 2 builds, thanks for saying.

**Comment by AnimMouse** [comment]
[gyan.dev](https://www.gyan.dev/ffmpeg/builds/) and [BtbN](https://github.com/BtbN/FFmpeg-Builds) are already providing GPL builds, it seems like it is better to just stop providing GPL builds than to provide what is already been provided by the two.

**Comment by 9001** [comment]
yeah I agree, especially the BtbN builds are nice since they're done through github actions just like yours 👍

**Comment by AnimMouse** [comment]
1054cd3edd1c8f8b23fe77b7722de5480edc14da

**Comment by AnimMouse** [comment]
[ffmpeg-autobuild-gpl](https://github.com/AnimMouse/ffmpeg-autobuild-gpl)

**Comment by AnimMouse** [comment]
https://github.com/ScoopInstaller/Main/pull/1454

**Comment by AnimMouse** [comment]
https://github.com/ScoopInstaller/Main/pull/1454#issuecomment-723687026

**Comment by AnimMouse** [comment]
https://github.com/GyanD/codexffmpeg/issues/15
