### ISSUE TITLE
No more FFmpeg builds since April 27th 2021?

### ISSUE THREAD

**Issue by Vangelis66** [AnimMouse/ffmpeg-autobuild#274]
Hello there @AnimMouse, I honestly hope you're safe and well 😄 

Thanks once more for these efforts 👍 and **especially for your x86 builds**, of which I am a consumer on my second (older) laptop, which runs **Vista Home Premium SP2 32-bit** and is fully updated (past Vista's EOL) with _WinServer 2008_ updates 😺 ...

As things stand, I am currently **subscribed to** ("watching") **this repo's releases** and I recently realised that the last release was on **2021/04/27**, namely 
https://github.com/AnimMouse/ffmpeg-autobuild/releases/tag/a-2021-04-27-03-00

In your README you state:

> Schedule
> 
> Release builds: Weekly or Every time ffmpeg-windows-build-helpers updates 
> or I updated the repository.

Has any of the above conditions changed?
Additionally, when I visited the **GitHub Actions** tab, I noticed that indeed the last successful workflow run was 
https://github.com/AnimMouse/ffmpeg-autobuild/actions/runs/787475254
which produced the builds I linked to above...
The ffmpeg snapshot compiled is `n4.5-dev-417-git-20210426-g63b2b0f`; 
**all subsequent workflow runs fail however**, and what's alarming for me is the fact that most fail at "**build (win32)**" stage 😢 ...
While looking at this, I saw that the last successful run 
https://github.com/AnimMouse/ffmpeg-autobuild/actions/runs/787475254
changed ffmpeg source `f7c3484...63b2b0f`, where `f7c3484` is actually 
`n4.5-dev-363-git-20210422-gf7c3484`
while, as stated, `63b2b0f` is 
`n4.5-dev-417-git-20210426-g63b2b0f`
i.e. more recent; but **all failing workflow runs have the older `f7c3484` snapshot as starting point** (which gets updated), isn't that a discrepancy? Why don't they try to "update" the more recent `63b2b0f` snapshot (i.e. the last most-up-to-date source successfully compiled) ?

Do you have any clues by now why the workflows past Apr 27th fail? Is it **upstream** (ffmpeg) code, **ffmpeg-build-helpers** code or **ffmpeg-autobuild** code? 
I practically have only [one other source](https://www.notion.so/34dc4ddf501a4b98b46ea9fb4f3470af?v=878345c5d88f4d21a6520db752b5c29f) of win32, Vista-compatible, FFmpeg builds, they, too, use **ffmpeg-build-helpers** to compile and they are successfully now at 
`ffmpeg-n4.5-dev-524-git-20210428-N-102169-g3a3e8c3-win32`, 
i.e. source two days newer that your **last** successful nightly build; 
sadly, they don't tell of the version (code snapshot) of the suite they're building with... 😞 

Being already highly indebted to you, I honestly hope this latest breakage can be successfully troubleshot and rectified... 
Best wishes, may the God[s] keep you well!

**Comment by Vangelis66** [comment]
Well, it looks like a fine mess currently, stuck in a bad-logic loop...
Latest failed runs:

https://github.com/AnimMouse/ffmpeg-autobuild/actions/runs/826397001

**build (win32)** fails because of 
```
Unknown option "--enable-avresample".
See ./configure --help for available options.
failed configure ffmpeg-source
Error: Process completed with exit code 1.
```
which is [FWBH #565](https://github.com/rdp/ffmpeg-windows-build-helpers/issues/565) fixed by https://github.com/rdp/ffmpeg-windows-build-helpers/commit/f38feb0387b3ae2a6a0c2e7b4fe00de542b7bc40, but the fix isn't available to the workflow, since FWBH is at an older snapshot, https://github.com/rdp/ffmpeg-windows-build-helpers/commit/bfd2c8c2d415d34538be980be8a3a613b7c66133 😞 

**build (win64)** is cancelled... 

And, IIUC, **ffmpeg source is reset** back to `f7c3484` from Apr 22nd ... 😠 

https://github.com/AnimMouse/ffmpeg-autobuild/actions/runs/826397049

FWBH gets updated to https://github.com/rdp/ffmpeg-windows-build-helpers/commit/75673910902f079a2b5347a11dc6c60952ad728c (which contains the fix for previous failure), so now **build (win32)** succeeds, but **yields a 32-bit binary based on code from 2021-04-22** 😞 ...

**build (win64)**: What would've been also a **64-bit binary based on code from 2021-04-22** fails to compile due to a new (64-bit specific?) error: 
```
Unknown option "--enable-libsvthevc".
See ./configure --help for available options.
failed configure ffmpeg-source
Error: Process completed with exit code 1.
```
which is [FWBH #564](https://github.com/rdp/ffmpeg-windows-build-helpers/issues/564); this hasn't yet been fixed upstream in code, but a workaround has been posted in https://github.com/rdp/ffmpeg-windows-build-helpers/issues/564#issuecomment-835860287

(Thinking selfishly aloud: If "we" **first** updated FWBH to current HEAD (`7567391`) (1st run) and **only afterwards** updated FFmpeg source to current HEAD (`8649f5d`) (2nd run), "we" would at least end up with `ffmpeg-8649f5d-win32-nonfree` artifacts 😜 , wouldn't "we"? - until FWBH #564 is resolved... )

**Comment by AnimMouse** [comment]
Hello there @Vangelis66 sorry that I can't reply immediately because I'm currently doing my studies for my upcoming graduation.

> Do you have any clues by now why the workflows past Apr 27th fail?

The inclusion of libsvthevc.

> it's unclear to me which snapshot of FWBH the workflow uses...

It seems like I need to add the git SHA of FWBH in the filename.

> which suggests the fix for FWBH #564 was still not available to the workflow

The fix for https://github.com/rdp/ffmpeg-windows-build-helpers/issues/564 is now here, I'm still debugging why it can't still pick up the patches required for building libsvthevc, maybe because of the usage of relative paths?
`git apply "../SVT-HEVC_git/ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch"`

Seems like the problem is related to this older problem https://github.com/rdp/ffmpeg-windows-build-helpers/issues/469#issuecomment-670606912 and the fix https://github.com/rdp/ffmpeg-windows-build-helpers/pull/478.

Currently studying the code in how to make it use absolute paths to the ffmpeg-source as this project uses custom ffmpeg-source-dir.

The 32 bit build succeeded because it does not build libsvthevc.

**Comment by AnimMouse** [comment]
This https://github.com/AnimMouse/ffmpeg-autobuild/pull/286 should fix this.

**Comment by Vangelis66** [comment]
A very belated, albeit **huge**, THANK YOU 🥇 for getting to the bottom of it and **successfully fixing** that breakage 👍 ... As things usually go, I got absorbed with other things and, sadly, I now realised I hadn't properly thanked you in a timely fashion... 😊 
 Considering it also required you submitting a PR to **FWBH**, extra praise is called for! ❤️ 

 Feeling somewhat guilty for destructing you from your studies 😉 , I wish you every success towards your graduation and long after that... 😃 

Best regards, thanks again!

**Comment by AnimMouse** [comment]
You're welcome. 😊

> Feeling somewhat guilty for destructing you from your studies 😉

Don't worry about it. 😉

Also, I compiled every FFmpeg builds I found on the internet [here](https://www.animmouse.com/p/ffmpeg-binaries/) if you need another source of builds.

**Comment by Vangelis66** [comment]
> Also, I compiled every FFmpeg builds I found on the internet [here](https://www.animmouse.com/p/ffmpeg-binaries/) 
> if you need another source of builds.

This has been highly appreciated! Many thanks! :tada: 

As a rule of thumb, builds compiled with Roger Pack's **FWBH** toolchain/script will be **Vista SP2** (and higher) **compatible**; so, that includes builds offered by **you**, **kusaanko**, **marierose147** and **Venomissimo** (he's the one, originally from **reddit**, that publishes **x86** builds on **notion.so**); **Reino**'s **win32** builds are patched to run on at least **WinXP SP3** with a **SSE**+ CPU; **Sherpya**'s **win32** builds ("MPlayer") also target at minimum **WinXP**, but he hasn't offered anything newer since last December... :disappointed: 

Your list is _almost_ complete, let me add some additional **unofficial** sources my exhaustive searches have yielded over recent years... :stuck_out_tongue_winking_eye: 
1. **win32** builds offered by "**AbeChin**":
http://blog.k-tai-douga.com/category/359294-1.html
latest compilation:
http://blog.k-tai-douga.com/article/188645532.html

**ffplay.exe** and **ffprobe.exe** will launch under at least **WinXP SP3**, he offers two **ffmpeg.exe** variants, one for **XP SP3** (and higher) and one for **Vista SP2** (and higher); he uses his own patched toolchains :+1: 

2. **maeyanie.com** win32+win64 builds: 
https://jenkins.maeyanie.com/job/ffmpeg/ 
https://jenkins.maeyanie.com/job/ffmpeg/lastSuccessfulBuild/artifact/

These are **automated** builds, part of **mpv** compilation, and are built using the **MXE** toolchain; the builds come with only a minimal set of third-party-libs, however they are **Vista SP2** (and higher) compatible (:+1:) ; the repo's retention policy is "latest-five-builds-**only**" :wink: ...

3. **win32** builds offered by **sudo-nautilus**: 
https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases

These use the same scripts/toolchain as the "official" **win64** builds by **BtbN**; like upstream, they do require you have **Windows 7 SP1** at minimum...

4. **wang-bin**'s Qt-AV (mostly) **shared** FFmpeg builds, for various platforms and OSes..
https://github.com/wang-bin/avbuild
https://sourceforge.net/projects/avbuild/files/windows-desktop/

The **desktop Win** builds are mostly **vanilla** (no-libs) FFmpeg builds, compiled natively with Visual Studio or cross compiled on **Ubuntu** with **clang** compiler; of the recent builds, only the ones needing **msvcrt120.dll** are Vista SP2 (**NT 6.0**) compatible, the rest would run under Win7+... 

I'm sure I've also come across a few other places offering **FFmpeg win builds**, but **have not bookmarked** them, either because they were **win64 exclusively** or the **win32** builds they provided wouldn't run on Vista... :sob: 
In any case, I'll be sure to add them **here** :smile: , that is if you're OK with that, should I stumble upon any more of them... 

Stay safe from Covid19, best wishes! :smiling_face_with_three_hearts:

**Comment by AnimMouse** [comment]
Thanks for that additional sources, I have added that to the list.

> In any case, I'll be sure to add them here 😄 , that is if you're OK with that, should I stumble upon any more of them...

I'm ok with that, that would be nice to have a list of all possible FFmpeg builds.
I'm also searching for more FFmpeg builds.

Stay safe also from COVID-19!
