### ISSUE TITLE
wma encoder

### ISSUE THREAD

**Issue by Israeldal** [AnimMouse/ffmpeg-autobuild#362]
hello there, i have a problem with ffmpeg wmav2 encoder, the audio quality is bad compared with the wma encoder that adobe audition, sound forge or dbpoweramp has. I just cant manage to compile ffmpeg or put a new codec if you can put the wma encoder of dbpoweramp to ffmpeg please, it would be great, dbpoweramp is free trial and its easy access to its codecs looking at files

adding more info: ffmpeg and the other prpgrams has the same wmav2 encoder ñ, so i dont know if its the version, but with adobe audition i can see with spectrogram that ffmpeg wma loses too many frequencies

adding more info: ffmpeg and the other programs has the same wmav2 encoder 
 so i dont know if its the version, but with adobe audition i can see with spectrogram that ffmpeg wma loses too many frequencies

[Windows Media Audio 10 poweramp.zip](https://github.com/AnimMouse/ffmpeg-autobuild/files/7071758/Windows.Media.Audio.10.poweramp.zip)

**Comment by AnimMouse** [comment]
Adding a new codec to FFmpeg is [somewhat hard to do](https://wiki.multimedia.cx/index.php/FFmpeg_codec_HOWTO) and supporting a proprietary codec is not one of the priorities of FFmpeg, that is why wmav2 support in FFmpeg is worse to the point that [it don't seem to be able to reach transparency at any given bitrate](https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio).

If you really want to use an open source FFmpeg to a proprietary codec like WMA, it is better just use an WMA CLI encoder [like this one](https://hydrogenaud.io/index.php?topic=90519.0) and pipe it to FFmpeg, that is also what I'm doing in using Apple's proprietary AAC codec (qaac, the best AAC encoder according to hydrogenaudio) in FFmpeg.

Or just ditch WMA altogether.
