### ISSUE TITLE
Please add this patch

### ISSUE THREAD

**Issue by megapro17** [AnimMouse/ffmpeg-autobuild#388]
https://ffmpeg.org/pipermail/ffmpeg-devel/2021-May/280189.html

**Comment by AnimMouse** [comment]
Sorry that I don't accept external patches to this repo, but I can help you to compile it in your own.
1. Fork this repo
2. Enable GitHub Actions on your fork. GitHub disables GitHub Actions in forks by default.
3. Download this patch and apply it to your own fork. The patch you said is included in my patch.
[0001-Add-application-of-patches.patch.gz](https://github.com/AnimMouse/ffmpeg-autobuild/files/7270851/0001-Add-application-of-patches.patch.gz)
4. Push, and let it compile.
I have added a code that will apply all the patches in the `ffmpeg-patches` directory.

**Comment by megapro17** [comment]
Thanks, nice ability. but I don't see any reason why it shouldn't be included, because it doesn't break any functionality, and even should be merged in original repo.

**Comment by Vangelis66** [comment]
@megapro17 

... I'm also after that patch, which mitigates the `ffmpeg` "bug" of not being able to mux (into the WEBM container) (some?) **raw HFR VP9** video streams produced by Google/Youtube ... 😠 

 This behaviour is not present in `ffmpeg <=3.0.1` and has already been reported to `ffmpeg`, but the devs there won't acknowledge it as a regression bug, rather shift the blame to Google for not producing compliant VP9 streams; so, it's unlikely `ffmpeg` will merge this patch in the foreseeable future 👎 ; read the whole thread in [this](https://github.com/ytdl-org/youtube-dl/issues/28042) `yt-dl` issue... 😉 

In that same thread, a **workaround** has been posted, courtesy of @nihil-admirari (👍 ) : 
```cmd
 -bsf:v "setts=pts=if(lt(DTS\, PREV_OUTDTS) * gte(PTS\, DTS)\, max(PTS\, PREV_OUTDTS)\, PTS):dts=max(DTS\, PREV_OUTDTS)"
```
This is only applicable if you're in possession of a fairly recent (after 2021-07-04) `ffmpeg` build...

I also appreciate ❤️ the effort taken by @AnimMouse to accommodate, but not all of us here on GitHub are seasoned coders with full knowledge on how to conduct "GitHub" operations the "right" way... 

> 3. Download this patch and apply it to your own fork. The patch you said is included in my patch.
[0001-Add-application-of-patches.patch.gz](https://github.com/AnimMouse/ffmpeg-autobuild/files/7270851/0001-Add-application-of-patches.patch.gz)
> 4. Push, and let it compile.
I have added a code that will apply all the patches in the ffmpeg-patches directory.

...might be **self-explanatory** to coders, but the layman `ffmpeg` user (that includes me 😊 ) is left pondering...

@megapro17 (or perhaps any other kind soul reading this 😉 ), will you be willing to submit a PR to the [FWBH](https://github.com/rdp/ffmpeg-windows-build-helpers/pulls) repo? 
Please, kindly take a look [here](https://github.com/ytdl-org/youtube-dl/issues/28042#issuecomment-918552542) as guidance 😄 ... If submitted and, hopefully, merged, then all GitHub projects using `GitHub  Actions + FWBH` will eventually, in future,  produce builds with the VP9 patch included... 

Thanks to all people involved in the various FFmpeg-related projects, your unwaning efforts aren't going unnoticed! ❤️

**Comment by megapro17** [comment]
thank you so much for that detailed instruction. i created a fork with that patch. I also added upx compression for binaries. Here if anyone needs it https://github.com/megapro17/ffmpeg-autobuild

**Comment by AnimMouse** [comment]
This patch has been merged upstream.
https://github.com/FFmpeg/FFmpeg/commit/68595b46cb374658432fff998e82e5ff434557ac
