### ISSUE TITLE
SVT AV1

### ISSUE THREAD

**Issue by rpdroky** [AnimMouse/ffmpeg-autobuild#619]
Could you kindly include libsvtav1 too? its way faster then libaom-av1

Thanks *_^

**Comment by AnimMouse** [comment]
`libsvtav1` is already included in the binaries. Try running `ffmpeg -hide_banner -h encoder=libsvtav1`.

**Comment by rpdroky** [comment]
Yre last build did the trick , i guess the build i used was outdated and that's why it didn't work , thanks aloot sir ! :)

**Comment by AnimMouse** [comment]
You're welcome!

**Comment by megapro17** [comment]
Wtf it did disappeared? 
```
ffmpeg version git-2022-12-04-6c81409-ffmpeg-windows-build-helpers
 DEV.L. av1                  Alliance for Open Media AV1 (decoders: libdav1d libaom-av1 av1 av1_cuvid av1_qsv ) (encoders: libaom-av1 av1_nvenc )
Codec 'libsvtav1' is not recognized by FFmpeg
```

**Comment by megapro17** [comment]
libvpx-vp9 is also missing bruh

**Comment by AnimMouse** [comment]
@megapro17 Somehow it got disabled on https://github.com/rdp/ffmpeg-windows-build-helpers/commit/286ba1aecf3cb51c8cd5a0b14d0148c316626464 because of this https://github.com/rdp/ffmpeg-windows-build-helpers/issues/655.
