### ISSUE TITLE
libvpx-vp9 encoder is missing in latest ffmpeg builds

### ISSUE THREAD

**Issue by suphamster** [AnimMouse/ffmpeg-autobuild#627]

**Comment by AnimMouse** [comment]
`--enable-libvpx` got commented out on https://github.com/rdp/ffmpeg-windows-build-helpers/commit/00a73a1cd9f2cc797ef95d81eb8fa5834b25786e#diff-e7c706509c0a0c2b3bffb6c3b5225dabaf63409a8952fa63985be062f3fbfcadR2382

**Comment by FransW5** [comment]
Why doesn't libvpx OR libvpx-vp9 work?
```
Unknown encoder 'libvpx'
Unknown encoder 'libvpx-vp9'
```

**Comment by AnimMouse** [comment]
https://github.com/rdp/ffmpeg-windows-build-helpers/pull/648

**Comment by AnimMouse** [comment]
Fixed. https://github.com/rdp/ffmpeg-windows-build-helpers/commit/9905dd7d1637a4c8b18e4b12d2fddd565c5a984b

**Comment by suphamster** [comment]
> Fixed. [rdp/ffmpeg-windows-build-helpers@9905dd7](https://github.com/rdp/ffmpeg-windows-build-helpers/commit/9905dd7d1637a4c8b18e4b12d2fddd565c5a984b)

Seems again same problem "Unknown encoder 'libvpx-vp9'" in latest builds...

**Comment by AnimMouse** [comment]
libvpx got disabled on https://github.com/rdp/ffmpeg-windows-build-helpers/commit/563e3d4f2978849b6e09f81251874c6ccc817ddb and enabled again on https://github.com/rdp/ffmpeg-windows-build-helpers/commit/13075b5850fea0f81993a03879cc786c3f19149f and yet gone.

**Comment by Fallenap** [comment]
Isn't it possible to make your builds from the same source that gyan dev uses? (git master branch)

**Comment by AnimMouse** [comment]
@Fallenap This repo is currently building from the same source that gyan dev uses (git master branch), the problem is in the [ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers) script.

**Comment by AnimMouse** [comment]
The [`--enable-libvpx` option](https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L2385) is located inside the [`if [[ $build_svt = y ]]; then` conditional statement](https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L2364). SVT was disabled by default on https://github.com/rdp/ffmpeg-windows-build-helpers/commit/286ba1aecf3cb51c8cd5a0b14d0148c316626464, causing the libvpx to be disabled also.
