### ISSUE TITLE
[Bug]: hevc nvenc broken in latest builds

### ISSUE THREAD

**Issue by suphamster** [AnimMouse/ffmpeg-autobuild#716]
I know that it's most likely "upstream" issue just let ppl know this. I have GTX 1060 and ffmpeg say that I don't have supported GPU that doesn't happen with builds about month and older.

**Comment by AnimMouse** [comment]
Kindly paste here the output of FFmpeg so that I can look what's wrong.

**Comment by suphamster** [comment]
`C:\Test\15>ffmpeg.exe -i "test2.webm" -c:v hevc_nvenc -b:v 200k -movflags +faststart -f mp4 -preset fast -c:a libopus -vbr on -compression_level 10 -b:a 40k test3.webm
ffmpeg version git-2022-11-22-98f6c59-ffmpeg-windows-build-helpers Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/ffmpeg-source --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 54.100 / 59. 54.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.101 /  8. 50.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test2.webm':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : IntroCine.mov
    artist          : VideoProc Converter
    encoder         : Lavf59.30.100
    comment         : IntroCine.mov
    genre           : Video
  Duration: 00:00:30.20, start: 0.000000, bitrate: 1199 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 1144 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.42.103 libx265
  Stream #0:1[0x2](eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 45 kb/s (default)
    Metadata:
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_nvenc))
  Stream #0:1 -> #0:1 (opus (native) -> opus (libopus))
Press [q] to stop, [?] for help
[hevc_nvenc @ 0000015028e06780] B frames as references are not supported
[hevc_nvenc @ 0000015028e06780] No capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libopus @ 0000015028e77e40] 1 frames left in the queue on closing
Conversion failed!`

**Comment by suphamster** [comment]
P.S. Plz don't ask why I convert to webm extention (real are ,mp4 coz using "-f mp4" command) this has nothing to do with problem and works on all older version.
P.P.S. Also I mentioned that latest version for nvenc in ffmpeg (in this case not hevc but h.264) is ask for driver update that I've done and h.264 nvenc became working but hevc still not even it didn't asked for driver update.

**Comment by suphamster** [comment]
Btw I found a similar issue some years ago and maybe now it's kinda the same
https://trac.ffmpeg.org/ticket/8254

**Comment by AnimMouse** [comment]
Can you try adding `-b_ref_mode disabled` flag in FFmpeg?
Example: `ffmpeg.exe -i "test2.webm" -c:v hevc_nvenc -b:v 200k -b_ref_mode disabled -movflags +faststart -f mp4 -preset fast -c:a libopus -vbr on -compression_level 10 -b:a 40k test3.webm`

**Comment by suphamster** [comment]
> ffmpeg.exe -i "test2.webm" -c:v hevc_nvenc -b:v 200k -b_ref_mode disabled -movflags +faststart -f mp4 -preset fast -c:a libopus -vbr on -compression_level 10 -b:a 40k test3.webm
Now it works fine, thanks. So I think this is issue is a repeat of that errror https://trac.ffmpeg.org/ticket/7746 again?

**Comment by AnimMouse** [comment]
In older versions of FFmpeg, by default, `-b_ref_mode` is set to `disabled`. In the newer versions of FFmpeg, `-b_ref_mode` is set to `-1`, I don't know what is that, since it is not yet documented by `ffmpeg -hide_banner -h encoder=hevc_nvenc`, but I'm assuming that it is `auto`. B frames as references are only supported on Turing and higher, GTX 1060 is Pascal, and FFmpeg tried to use B frames as references on a Pascal GPU, causing that error.

Ticket [#7746](https://trac.ffmpeg.org/ticket/7746) and [#8809](https://trac.ffmpeg.org/ticket/8809) has nothing to do with this.

**Comment by AnimMouse** [comment]
What do you use `-compression_level 10` for? Can you remove that option and `-b_ref_mode disabled` and see if it still error?

**Comment by suphamster** [comment]
> Owner
This is for ogg better compression but I may be wrong, anyway removing both didn't helped. Btw do u know how disabling 
'b_ref_mode' affects video quality?

**Comment by AnimMouse** [comment]
B frames as references will not affect the video quality, but the file size. Having B frames as references enabled will reduce the video file size at the same quality. Since your video card does not support B frames as references, just forget about it until you upgrade your video card.

Commit https://github.com/FFmpeg/FFmpeg/commit/a0949d0bcb0eee2f3fffcf9a4810c0295d14c0dc and https://github.com/FFmpeg/FFmpeg/commit/28680e2f41b93b75863720e42397441dfcc29f94 sets the `-b_ref_mode` default to `-1`.

**Comment by AnimMouse** [comment]
This might be an upstream bug, since FFmpeg should not use `-b_ref_mode` on by default on Pascal GPUs. Can you make a report to [FFmpeg bug tracker](https://trac.ffmpeg.org)? Just follow [these instructions](https://ffmpeg.org/bugreports.html) when submitting one.

**Comment by suphamster** [comment]
> This might be an upstream bug, since FFmpeg should not use `-b_ref_mode` on by default on Pascal GPUs. Can you make a report to [FFmpeg bug tracker](https://trac.ffmpeg.org)? Just follow [these instructions](https://ffmpeg.org/bugreports.html) when submitting one.

Ok, created ticke https://trac.ffmpeg.org/ticket/10093#ticket - is it good enought?

**Comment by AnimMouse** [comment]
Yes, that's good enough.

**Comment by AnimMouse** [comment]
Since this issue is now out of scope of this repository, this issue is in the hands of FFmpeg developers now, I will now close this issue. I hope they will fix it.

**Comment by AnimMouse** [comment]
Fixed on https://github.com/FFmpeg/FFmpeg/commit/7a8560cb22dd9f5c54df71af3fef26db9a2a28b0
https://trac.ffmpeg.org/ticket/10093#comment:3
