### ISSUE TITLE
JPEG-XL

### ISSUE THREAD

**Issue by zedd-0** [AnimMouse/ffmpeg-autobuild#956]
please add support for JPEG-XL.
--enable-libjxl

**Comment by AnimMouse** [comment]
Since this repository only builds on what rdp/ffmpeg-windows-build-helpers has, I recommend that you create an issue separately on [rdp/ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers/issues) about adding support for JPEG-XL.

**Comment by Ciancy28** [comment]
Both this issue and #1071 are closed, but to this day no jpeg-xl encoder/decoder seems to be present in these builds.

```
[vist#0:0/jpegxl @ 0000016888728f00] Decoding requested, but no decoder found for: jpegxl
Error opening output file output.bmp.
Error opening output files: Invalid argument
```

```
[vost#0:0 @ 000001df60cca680] Automatic encoder selection failed Default encoder for format image2 (codec jpegxl) is probably disabled. Please choose an encoder manually.
[vost#0:0 @ 000001df60cca680] Error selecting an encoder
Error opening output file output.jxl.
Error opening output files: Encoder not found
```

```
[vost#0:0 @ 00000174c4b5a980] Unknown encoder 'libjxl'
[vost#0:0 @ 00000174c4b5a980] Error selecting an encoder
Error opening output file output.jxl.
Error opening output files: Encoder not found
```

I'm a bit confused by this, is there something that i'm missing?

**Comment by AnimMouse** [comment]
@Ciancy28 This is closed since this is an upstream issue.
