### ISSUE TITLE
How to extract encrypted mpegts

### ISSUE THREAD

**Issue by atplsx** [AnimMouse/ffmpeg-autobuild#975]
Hı
How to decyrpt mpegts with ffmpeg
Please Can you show me how to configure it to do this? I take the error decryption_key option not found

**Comment by AnimMouse** [comment]
Place `-decryption_key` before `-i` like this `ffmpeg -decryption_key <key> -i <file>`.

**Comment by atplsx** [comment]
ffmpeg -decryption_key e7b8e75466530c3cf7238f577e18618a -i 0000000100000002STR.ts -c:a copy -c:v copy decrypted.ts
ffmpeg version git-2023-10-23-ff5a357-ffmpeg-windows-build-helpers Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-gnutls --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-libaribcaption --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/ffmpeg-source --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      58. 27.100 / 58. 27.100
  libavcodec     60. 30.102 / 60. 30.102
  libavformat    60. 15.100 / 60. 15.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  4.100 /  7.  4.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Option decryption_key not found.
Error opening input file 0000000100000002STR.ts.
Error opening input files: Option not found


ffmpeg -cenc_decryption_key e7b8e75466530c3cf7238f577e18618a -i 0000000100000002STR.ts -c:a copy -c:v copy decrypted.ts
ffmpeg version git-2023-10-23-ff5a357-ffmpeg-windows-build-helpers Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-gnutls --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-libaribcaption --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/ffmpeg-source --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      58. 27.100 / 58. 27.100
  libavcodec     60. 30.102 / 60. 30.102
  libavformat    60. 15.100 / 60. 15.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  4.100 /  7.  4.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Option cenc_decryption_key not found.
Error opening input file 0000000100000002STR.ts.
Error opening input files: Option not found

ffmpeg -cryptokey e7b8e75466530c3cf7238f577e18618a -i 0000000100000002STR.ts -c:a copy -c:v copy decrypted.ts
ffmpeg version git-2023-10-23-ff5a357-ffmpeg-windows-build-helpers Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-gnutls --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-libaribcaption --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/ffmpeg-source --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      58. 27.100 / 58. 27.100
  libavcodec     60. 30.102 / 60. 30.102
  libavformat    60. 15.100 / 60. 15.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  4.100 /  7.  4.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mpegts, from '0000000100000002STR.ts':
  Duration: N/A, bitrate: N/A
Output #0, mpegts, to 'decrypted.ts':
[out#0/mpegts @ 0000026bbb5bf440] Output file does not contain any stream
Error opening output file decrypted.ts.
Error opening output files: Invalid argument

**Comment by AnimMouse** [comment]
It seems like FFmpeg's mpegts muxer does not support decryption, hence the error `Option decryption_key not found.`, can you try this instead: `ffmpeg -key <key> -iv <initialization vector> -i crypto+file:<file>`

Example:
`ffmpeg -key e7b8e75466530c3cf7238f577e18618a -iv <your initialization vector> -i crypto+file:0000000100000002STR.ts -c:v copy -c:a copy decrypted.ts`

More infos:
[[FFmpeg-user] How to decrypt .ts files into separate .ts files with ffmpeg without using a playlist?](https://www.mail-archive.com/ffmpeg-user@ffmpeg.org/msg24056.html)
[How to decrypt segmented parts .ts files which are encrypted with ffmpeg?](https://stackoverflow.com/questions/68618121/how-to-decrypt-segmented-parts-ts-files-which-are-encrypted-with-ffmpeg)

**Comment by atplsx** [comment]
Thank you
I've read these before. It doesn't do anything. Do I need to do anything different during the configuration or compilation phase?

**Comment by AnimMouse** [comment]
> I've read these before. It doesn't do anything.

Can you paste here the outputs?

> Do I need to do anything different during the configuration or compilation phase?

Nope, all FFmpeg builds have decryption functionality inside. If you still can't decrypt your mpegts file even with the instructions above, maybe your file is corrupted, your encryption key is incorrect, or your mpegts file uses some obscure encryption algorithm that neither FFmpeg nor OpenSSL can decrypt.

**Comment by atplsx** [comment]
can you help me please read 
https://github.com/tsduck/tsduck/issues/1329

**Comment by AnimMouse** [comment]
> I don't know what the -iv value is, but I explained the same things in the link above. I can decrypt the encrypted file https://github.com/openlgtv/epk2extract with this program and I do not use any -iv value.

It means that the program [openlgtv/epk2extract](https://github.com/openlgtv/epk2extract) knows what should be the IV (initialization vector) is, you can try contacting the creator of the program what is the default IV value for that encryption specifically on LG TVs.

**Comment by atplsx** [comment]
Thank you for all
I didn't see them replying to anyone at all

**Comment by AnimMouse** [comment]
> thank you for your effort
I didn't see them replying to anyone at all

You're welcome. If you got your IV (initialization vector), you will be able to decrypt your file.
